---
title: "Rproj template"
author: "Jouni Vatanen"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output: 
  html_document: 
    toc: TRUE
    toc_depth: 2
    number_sections: FALSE
    df_print: paged
    code_folding: hide
    css: "./doc/Ilmarinen.css"
editor_options: 
  chunk_output_type: console
---

```{r setup, echo = FALSE, results = "hide", warning = FALSE, message = FALSE}
# SETUP

# PACKAGES AND FUNCTIONS
# Pacman loads and installs packages
if (!require("pacman")) install.packages("pacman")

# Checkpoint installs packages from a given date for reproduction
pacman::p_load("checkpoint") 

# Use the date few weeks after R-3.5.3. was released
checkpoint("2019-04-01", scanForPackages = FALSE,
           checkpointLocation = Sys.getenv("USERPROFILE"))

# Usermade general custom functions
pacman::p_load_gh("JouniVatanen/Jmisc") 

# Load and install packages
pacman::p_load(
  "extrafont", "readxl", "tidyverse", "tidyr", "data.table", "magrittr" 
  , "lubridate", "knitr", "modelr", "broom", "caret", "desctable", "formattable" 
  #, "grid", "gridExtra", "DT", "tm", "wordcloud", "SnowballC", "stringi"
  #, "keyring", "DBI", "odbc", "dbplyr"
  #, "Hmisc", "GGally", "kableExtra", "FactoMineR", "factoextra", "ClustOfVar", 
  #, "ggrepel", "pROC", "webshot", "xts", "psych", "htmlwidgets"
  )

# Note:  there is some trouble installing RDCOMClient. 
# 1. Install Rtools 
# 2. Add variables to your path 
# 3. Install from github
#devtools::install_github("omegahat/RDCOMClient")

# Check if Arial fonts are installed and install, if they are not
if (!any(match(fonts(), "Arial"), na.rm = TRUE)) {
  font_import(pattern = "arial.*", prompt = FALSE)
}

# Load functions
source("./R/functions.R", encoding = "UTF-8")

# Set variables to be used in keyring.
#kr_service <- "my_service"
#kr_username <- "my_username"

# If keyring service is not yet defined, then define password
#if (is.na(key_list(kr_service)[1, 2])) {
#  warning("Check the kr_username and save your password to keyring")
#  keyring::key_set(service = kr_service, username = kr_username)
#}

# Define global options FALSE and knitr options
knitr::opts_chunk$set(warning = F, error = F, message = F, echo = F)

# Change knit table option NA to empty
options(knitr.kable.NA = "", OutDec = ",")
locale.fi <- locale(date_names = "fi", decimal_mark = ",", grouping_mark = " ")
```

```{r knit-document, eval = FALSE}
# Activate to create a html file
rmarkdown::render("Rproj-template.Rmd", 
  output_format = "html_document", 
  output_dir = "./output", 
  encoding = "UTF-8")
```

# Johdanto

Miksi tämä työ on tehty ja joitain tarvittavia linkkejä

```{r load-data, eval = FALSE}
# Load data
# Load single csv
df.2018 <- fread("./data/data.csv", 
                 select = col.select, 
                 encoding = "UTF-8", 
                 check.names = TRUE)

# Load single xls/xlsx sheet
df.2018 <- read_excel("./data/data.xlsx")

# Load multiple xls/xlsx sheets
# Choose sheet names or numbers and load using purr
df.2018 <- c("Sheet 1", "Sheet 2", "Sheet 3")
  map_df(~ read_excel("./data/data.xlsx", sheet = .x))

# Load multiple xls/xlsx files
# Choose patterns for file names and load using purrr
df.2018 <- list.files("./data", "Osallistujat", full.names = TRUE) %>%
  map_df(~ read_excel(.x))

```

```{r mutate-data, eval = FALSE}
# Mutate and combine data
# Recode and classify
koulutus.class <- rlang::exprs(
  "1 Ylempi korkeakoulu"                = "Yliopisto/korkeakoulu",
  "2 AMK"                               = "Ammattikorkeakoulu",
  "3 Ylioppilas"                        = "Ylioppilas/opisto",
  "4 Perus-/ ammattikoulu"              = "Kansa-/perus-/keski-/ammattikoulu",
  "5 EOS"                               = "Valitse")

statement.levels <- c(
  "täysin eri mieltä", 
  "jokseenkin eri mieltä", 
  "ei samaa eikä eri mieltä", 
  "jokseenkin samaa mieltä", 
  "täysin samaa mieltä")

satisfaction.levels <- c(
  "erittäin huonosti",
  "huonosti",
  "tyydyttävästi",
  "hyvin",
  "erittäin hyvin")

numeric.conv <- c(
  "^yksi$" = "1",
  "^kaksin$" = "2",
  "^kolme$" = "3",
  "^neljä$" = "4",
  "^viisi$" = "5",
  "^kuusi$" = "6",
  "^seitsemän$" = "7",
  "^kahdeksan$" = "8",
  "^yhdeksän$" = "9",
  "^kymmenen$" = "10")

factor.levels <- c("", "", "", "")

# If you want to combine many df, then rename, select and give a version name
df.2018 %<>%
  mutate(version = "v2018") %>%
  rename() %>%
  select() %>%
  left_join(df.db.2018, by = "id")

# Create a data that contains all the open feedback
df.feedback <- df.2018 %>%
  select() %>%
  mutate_all(funs(ifelse(. %in% c(
    "Kyllä, missä asioissa?", 
    "En, mitä tietoa kaipasit?", 
    "Kyllä", 
    "En",
    "Jollain muulla tavalla, miten?", 
    "-", "--"), 
    NA, .))) %>%
  rename_all( ~ c(
    "var 1",
    "var 2")) %>%
  gather(2:ncol(.), key = "question", value = "values") %>%
  filter(!is.na(values)) %>%
  arrange(question, values)

# Mutate the data
df.numeric <- df.2018 %>%

  # Join area codes
  left_join(select(df.pono, 1, 7, 11, 13), 
    by = c("POSTINUMERO_1" = "Postinumeroalue")) %>%
  
  # Strip information from social security number
  mutate_at(vars(HETU), 
            funs(Sukupuoli = Jmisc::calc_gender(.),
                 Synt.pvm = Jmisc::calc_birth(.))) %>%
  
  # Calculate age
  mutate(Ika = interval(birth, today) / years(1)) %>%
  
  # Change statements to factors and remove EOS
  mutate_at(vars(1:3), 
            funs(as.numeric(parse_factor(., statement.levels, 
                                         na = c("", "NA", "en osaa sanoa"), 
                                         include_na = FALSE)))) %>%
  
  # Classify variablesage, pension amount and pension type
  mutate(var1 = cut(var, c(0, 54.9, 59.9, 62.9, 64, 999), 
      labels = c("", "", "", "", "", "", "")),
    var2 = case_when(
      var %in% c("") ~ "case1",
      var %in% c("") ~ "case2",
      TRUE ~ .)) %>%
  
  # Generate 0-100 variables
  mutate_at(vars(1), funs(ifelse(is.na(.), 0, 100))) %>%
  mutate_at(vars(2), funs(case_when(
    is.na(.)     ~ NA_real_,
    . == "Kyllä" ~ 100,
    TRUE         ~ 0))) %>%
  mutate_at(vars(3), funs(case_when(
    is.na(.)    ~ NA_real_,
    . == "En"   ~ 0,
    TRUE        ~ 100))) %>%
                            
  # Calculate NPS
  mutate_at(vars(4), funs(NPS = Jmisc::calc_nps(.))) %>%
  
  # Modify to factors with levels and custom NA values
  mutate_at(vars(5), funs(
    parse_factor(., factor.levels, na = c("", "NA", "EOS")))) %>%
  
  # To factors
  mutate_at(vars(6), funs(as.factor(.))) %>%
  
  # Leave only necessary variables
  select(NPS, 1:10) %>%
  
  # Rename for descriptive table
  rename_all( ~ stri_replace_all_regex(., c("^(.{1,7}):", "[;?!=,]", " "), 
                                       c("Q$1", "", "."), 
                                       vectorize_all = FALSE))

```

```{r create-table, eval = FALSE}
# Create statistics table
# Choose data and columns to factor and group by
df.desc <- Jmisc::desc_stat(df.numeric, c(1:10), c("var1", "var2"))
```

```{r mutate-table, eval = FALSE}
# Mutate statistics table
df.desc %<>%
  
  # Add extra rows
  add_row(Variables = "") %>%
  add_row(Variables = "TAUSTATIEDOT") %>%
  
  # Slice the data to the correct form
  slice(c(1:5, 2, 10)) %>%
  
  # Fix variable names and remove unnecessary variables
  #mutate_at(vars(Variables), funs(str_replace_all(. , "\\.", "\\s"))) %>%
  mutate_at(vars(Variables), 
            funs(stri_replace_all_regex(., c("^Q[0-9 ]{1,7}"), c(""), 
                                        vectorize_all = FALSE))) %>%
  mutate_at(vars(Variables), funs(case_when(
    . == "100" ~ "suosittelija",
    . == "0" ~ "neutraali",
    . == "-100" ~ "kriittinen",
    . == "1" ~ "täysin eri mieltä",
    . == "2" ~ "jokseenkin eri mieltä",
    . == "3" ~ "ei samaa eikä eri mieltä",
    . == "4" ~ "jokseenkin samaa mieltä",
    . == "5" ~ "täysin samaa mieltä",
    TRUE ~ .))) %>%
  
  # Rename variables
  rename(
    Suosittelija = `100`, 
    Neutraali = `0`,
    Kriittinen = `-100`) %>%
  
  # Remove futile variables
  select(-starts_with("V1"))
```

```{r data-to-txt, eval = FALSE}
# Export data to txt-file
Jmisc::df_to_txt(df.desc, "./output/desc_table.txt")
Jmisc::df_to_txt(df.feedback, "./output/data_feedback.txt")
Jmisc::df_to_txt(df.2018, "./output/data_cleaned_2018.txt")
```

```{r data-to-desc-txt, eval = FALSE}
# Create basic output to inspect the file
Jmisc::inspect(df.2018, "output/desc_example.txt")
```

# Tiivistelmä

Yhteenveto ja johtopäätökset

# Tulokset

## Peruskuvat

```{r create-fig-basic, eval = FALSE}
# Basic plot
# Choose which variables to plot
l <- list(1, 2, c(3:5), 6, 7)

# Edit labels to fit the screen properly
labels <- c("var.name")

# Choose which variables to plot and map the function to a list
plot.basic <- df.desc %>% 
  select(1:2) %>%
  rename_at(1, funs(str_sub(., 1, 30))) %>%
  {map(l, function(x) Jmisc::multiplot_bars(., x, labels))}

# Length of the list for a calculation to correct figure size
# Height of 6 for each row of pictures
len <- as.integer(round(length(plot.basic) / 2, 0) * 3)
```

```{r show-fig-basic, out.width = "100%", fig.height = len}
# Create and show a grid from plots
do.call("grid.arrange", c(plot.basic, ncol = 2))
```

## Tulostaulukko

```{r show-table, eval = FALSE}
# Show table
df.desc %>%
  mutate_at(vars(-1), funs(round(., 1))) %>%
  mutate_at(vars(-1), funs(ifelse(is.na(.), "", .))) %>%
  datatable(rownames = FALSE, extensions = c("Buttons", "FixedColumns"), 
    options = list(
      pageLength = 10, 
      scrollX = TRUE, 
      lengthMenu = list(c(10, -1), list("10", "All")), 
      dom = "Blrtip", buttons = list(
        "copy",  
        list(
          extend = "excel", 
          filename = "Ilmarinen"), 
        list(
          extend = "colvis", 
          text = "Näytä/piilota sarakkeita", 
          columns = ":gt(1)", 
          show = ":lt(2)", 
          hide = ":gt(1)"), 
        list(
          extend = "colvisGroup", 
          text = "Piilota kaikki", 
          show = ":lt(2)", 
          hide = ":gt(1)"))))
```

### Sanapilvi

```{r wordcloud, out.width = "100%"}
# Create remove words list
remove.words <- c("että", "moite", "sitä", "sitä", "sen", "palaute", "fffd", 
                  "hei", "myös")

# Stem and remove stopwords for further analyses
corpus <- Corpus(VectorSource(df.feedback["values"]))
dtm <- TermDocumentMatrix(corpus, control = list(
  removePunctuation = TRUE,
  removeNumbers = TRUE,
  tolower = TRUE,
  stopwords = c(stopwords("finnish"), remove.words),
  stripWhitespace = TRUE))

vec <- sort(rowSums(as.matrix(dtm)), decreasing = TRUE)
df <- data.frame(word = names(vec), freq = vec)

# Create wordcloud and give a random number seed
par(mar = rep(0, 4))
set.seed(31102018)
wordcloud(df$word, df$freq, min.freq = 1, max.words = 200, rot.per = 0, 
          colors = ilmarinen_cols())
```

### Yksittäiset palautteet

```{r include = FALSE}
# This is needed for the feedback work
DT::datatable(df.feedback, extensions = "Buttons",
  options = list(
    pageLength = 5, scrollX = TRUE, dom = "Blrtip",
    buttons = list("copy", list(
      extend = "excel", filename = "Avopalaute"))))
```

```{r results = "asis"}
# All feedback in its own boxes
for (i in unique(df.feedback$question)) {
  
  DT.i <- df.feedback %>%
    dplyr::filter(question == i) %>%
    dplyr::select(values)
  
  cat("\n\n")
  print(htmltools::tagList(
    DT::datatable(DT.i, 
      rownames = FALSE, 
      colnames = c(i), 
      extensions = "Buttons",
      options = list(
        pageLength = 5, scrollX = TRUE, dom = "Blrtip",
        lengthMenu = list(c(5, -1), list('5', 'All')),
        buttons = list("copy", list(
          extend = "excel", filename = "Avopalaute"))))))
  cat("\n\n")
}
```
